### PR TITLE
Small edit in the example code

### PR DESCRIPTION
**Pull request by aepod**
minor fix

### CODE REVIEW

**Comment by voleye** [comment]
@aepod thank you for contribution!

Internal ticket: MAGETWO-42852

**Comment by aepod** [comment]
Gladly. I am having other issues getting this to work, going to document and create an issue. Running through everything on a clean vm right now.

**Comment by aepod** [comment]
I finally figured out what my trouble was. When installing from CLI you need to be in the bin/ directory. This is clearly denoted in the documentation, but the example does not have this in it. I will be pulling my PR, and submitting a new one that shows this.

**Comment by voleye** [comment]
The class `\Magento\SampleData\Model\SampleData` has been changed recently fb41d4b70ea262006f15ce0a3ff2530241a4e5f1

Could it be related to the issue that you pointed out?

**Comment by davidalger** [comment]
@aepod I just installed successfully from the magento root dir. The CLI commands I used were in the form of `bin/magento foo`

**Comment by aepod** [comment]
I suspect it is either RHEL 7 (SELinux in Permissive), or an issue with the Zend Server. I will be repeating the tests in the next couple days, and collecting enough notes to start an issue where needed.

Thanks for the update @davidalger. I had tried to install in that way several times. The documentation I was referring to that says you have to be in the bin dir is here:
http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html

`You must install Magento from its bin subdirectory.`

**Comment by davidalger** [comment]
@aepod Ah. Guess that doc is out of date… ;)

**Comment by xcomSteveJohnson** [comment]
Thanks for pointing that out. I'll address it.

It's not that something is out of date, there are alternative ways to do the same thing. The statement would be better as something more general like "the commands are located in the bin directory" rather than saying you have to run the commands from that directory.

**Comment by voleye** [comment]
README.md file was updated, so I close this PR.

**Pull request closed without merging**
