### PR TITLE
Fix for incorrect magento2 sample data 

### PR DESCRIPTION
**Pull request by nkvp**
**Issue:** 
Sample data widgets were not loading on non anchor sample categories as these were marked as anchor categories in sample data

**Fix:**
This fixes sample data to point to correct category type. 

e.g magento2-sample-data/app/code/Magento/ConfigurableSampleData/fixtures/categories.csv shows that category "Women" is not an anchor category, yet magento2-sample-data/app/code/Magento/WidgetSampleData/fixtures/cmsblock.csv mentions it as an anchor category causing it not to get loaded successfully

### CODE REVIEW

**Comment by slavvka** [comment]
@magento run all tests

**Review by slavvka — APPROVED** [review]

**Comment by slavvka** [comment]
Hi @nkvp Looks like your changes breaks DBC build. Could you please take a look?

**Comment by engcom-Alfa** [comment]
Hi, @nkvp .

Unfortunately, we are not able to reproduce this issue on 2.4-develop.
Widgets are successfully loaded on non-anchor categories, like **Women**

**Preconditions:**

Magento 2.4-develop
Sample Data

**Manual testing scenario:**

1. Go to Admin->Content->Widgets;
2. Select one widget from the list for edit (**Training Category Content** for example);
3. In **Layout Updates** set:
Screenshot from 2020-05-26 16-32-35
4. Save widget
5. Go to Storefront -> **Women**  category;

**Actual Result:** :heavy_check_mark:  The widget is displayed on the **Women** category page
Screenshot from 2020-05-26 16-35-57

@nkvp Could you provide us additional information or steps on how to reproduce this issue?

Thanks!

**Comment by nkvp** [comment]
Closing PR temporarily as there are issues with the fix. Will re-test on latest build and open if necessary.

**Pull request closed without merging**
