### PR TITLE
Fix PHP Fatal error on sampledata:install routine

### PR DESCRIPTION
**Pull request by davidalger**
The latest push to the magento2 develop branch breaks the sample data. Attempts to install fail due to referencing a now non-existant constant:

```
PHP Fatal error:  Undefined class constant 'FIELD_NAME_VALIDATION_STRATEGY' in /server/sites/m2.dev/var/tmp/m2-data/app/code/Magento/SampleData/Module/ConfigurableProduct/Setup/Product.php on line 84
PHP Stack trace:
PHP   1. {main}() /server/sites/m2.dev/bin/magento:0
PHP   2. Symfony\Component\Console\Application->run() /server/sites/m2.dev/bin/magento:25
PHP   3. Symfony\Component\Console\Application->doRun() /server/sites/m2.dev/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /server/sites/m2.dev/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /server/sites/m2.dev/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   6. Magento\SampleData\Console\Command\SampleDataInstallCommand->execute() /server/sites/m2.dev/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP   7. Magento\SampleData\Model\SampleData->install() /server/sites/m2.dev/var/tmp/m2-data/app/code/Magento/SampleData/Console/Command/SampleDataInstallCommand.php:102
PHP   8. Magento\SampleData\Model\Installer->run() /server/sites/m2.dev/var/tmp/m2-data/app/code/Magento/SampleData/Model/SampleData.php:96
PHP   9. Magento\SampleData\Module\ConfigurableProduct\Setup->run() /server/sites/m2.dev/var/tmp/m2-data/app/code/Magento/SampleData/Model/Installer.php:113
PHP  10. Magento\SampleData\Module\ConfigurableProduct\Setup\Product->run() /server/sites/m2.dev/var/tmp/m2-data/app/code/Magento/SampleData/Module/ConfigurableProduct/Setup.php:34

Fatal error: Undefined class constant 'FIELD_NAME_VALIDATION_STRATEGY' in /server/sites/m2.dev/var/tmp/m2-data/app/code/Magento/SampleData/Module/ConfigurableProduct/Setup/Product.php on line 84

Call Stack:
    0.0002     229368   1. {main}() /server/sites/m2.dev/bin/magento:0
    2.9139   63247472   2. Symfony\Component\Console\Application->run() /server/sites/m2.dev/bin/magento:25
    2.9155   63292104   3. Symfony\Component\Console\Application->doRun() /server/sites/m2.dev/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    2.9157   63293056   4. Symfony\Component\Console\Application->doRunCommand() /server/sites/m2.dev/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    2.9157   63293536   5. Symfony\Component\Console\Command\Command->run() /server/sites/m2.dev/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    2.9159   63297368   6. Magento\SampleData\Console\Command\SampleDataInstallCommand->execute() /server/sites/m2.dev/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
    2.9173   63325144   7. Magento\SampleData\Model\SampleData->install() /server/sites/m2.dev/var/tmp/m2-data/app/code/Magento/SampleData/Console/Command/SampleDataInstallCommand.php:102
    3.7413   70781968   8. Magento\SampleData\Model\Installer->run() /server/sites/m2.dev/var/tmp/m2-data/app/code/Magento/SampleData/Model/SampleData.php:96
   89.9485  146883664   9. Magento\SampleData\Module\ConfigurableProduct\Setup->run() /server/sites/m2.dev/var/tmp/m2-data/app/code/Magento/SampleData/Model/Installer.php:113
   89.9485  146884088  10. Magento\SampleData\Module\ConfigurableProduct\Setup\Product->run() /server/sites/m2.dev/var/tmp/m2-data/app/code/Magento/SampleData/Module/ConfigurableProduct/Setup.php:34

```

Note: I did not research alternatives to the removed argument. Based on the validation strategy used and the sample data installing with no errors, it may not be necessary any more.

### CODE REVIEW

**Comment by voleye** [comment]
Hi @davidalger , thank you for this pull request and continued support to Magento 2!

We will try fix the issue in short terms.

**Comment by voleye** [comment]
Internal ticket: MAGETWO-43448

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments below.

**Comment by voleye** [comment]
Fixed

Please, use the following map of "Sample Data" availability:
Stable version available through
 - Composer (packages.magento.com version 1.0.0-beta5)
 - VCS (https://github.com/magento/magento2-sample-data, branch "merchant_beta")

Develop version available through
 - VCS (https://github.com/magento/magento2-sample-data, branch "develop")

**Comment by xcomSteveJohnson** [comment]
FWIW, in current builds, sampledata:install either doesn't exist or won't work. Please see: http://bit.ly/1M39SUw

**Comment by davidalger** [comment]
@xcomSteveJohnson There is now a sampledata:deploy command in the develop version of the bin/magento tool. At a glance it appears to do things differently, but didn't have time to play with it to see if it worked completely as it should. :)

**Comment by xcomSteveJohnson** [comment]
Doubtful because the corresponding sample data packages are not on packages.magento.com.

**Pull request closed without merging**
